%YAML 1.2
---
name: 'kb1-128x14'                      # ideally no spaces
gpu: 1                                 # gpu id to process on

dataset: 
  num_chunks: 1000000                   # newest nof chunks to parse
  train_ratio: 0.95                    # trainingset ratio
  # For separated test and train data.
  # input_train: '/path/to/chunks/*/draw/' # supports glob
  # input_test: '/path/to/chunks/*/draw/'  # supports glob
  # For a one-shot run with all data in one directory.
  input: '/root/training-data/'

training:
    batch_size: 2048                   # training batch
    test_steps: 5000                   # eval test set values after this many steps
    train_avg_report_steps: 500        # training reports its average values after this many steps.
    total_steps: 10000000                # terminate after these steps
    warmup_steps: 250                  # if global step is less than this, scale the current LR by ratio of global step to this value
    checkpoint_steps: 50000          # optional frequency for checkpointing before finish
    shuffle_size: 524288               # size of the shuffle buffer
    lr_values:                         # list of learning rates
        - 0.02
        - 0.002
        - 0.0005
    lr_boundaries:                     # list of boundaries
        - 100000
        - 130000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss
    path: '/root/networks'    # network storage dir
    moves_left_loss_weight: 0.01

model:
  filters: 128
  residual_blocks: 14
  se_ratio: 0.25
...
